#
#   build
#
FROM maven:3.9.0-eclipse-temurin-17-alpine as build

COPY src/ /home/app/src
COPY pom.xml /home/app/

RUN mvn -q -f /home/app/pom.xml clean package -Pjava11 -Dmaven.test.skip=true

#
#   pack with Wildfly
#
FROM jboss/wildfly:25.0.0.Final

COPY --from=build /home/app/target/jax-rs-template-1.0.0/ /opt/jboss/wildfly/standalone/deployments/app.war/
RUN touch /opt/jboss/wildfly/standalone/deployments/app.war.dodeploy

ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

EXPOSE 8080
ENTRYPOINT ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]