#
#   build
#
FROM maven:3.8.4-openjdk-17-slim as build

COPY src/ /home/app/src
COPY pom.xml /home/app/

RUN mvn -q -f /home/app/pom.xml clean package -Dmaven.test.skip=true

#
#   pack with Jetty
#
FROM jetty:11.0.7-jdk17-slim

COPY --from=build /home/app/target/jax-rs-template-1.0.0/ /var/lib/jetty/webapps/root/

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/usr/local/jetty/start.jar"]
