#
#   build
#
FROM maven:3.9.0-eclipse-temurin-17-alpine as build

COPY src/ /home/app/src
COPY pom.xml /home/app/

RUN mvn -q -f /home/app/pom.xml clean package -Dmaven.test.skip=true

#
#   pack with Tomcat
#
FROM tomcat:11.0.0-jre17-temurin

COPY --from=build /home/app/target/jax-rs-template-1.0.0/ /usr/local/tomcat/webapps/ROOT/

EXPOSE 8080
ENTRYPOINT ["catalina.sh", "run"]