#
#   build
#
FROM maven:3.9.0-eclipse-temurin-17-alpine as build

COPY src/ /home/app/src
COPY pom.xml /home/app/

RUN mvn -q -f /home/app/pom.xml clean package -Dmaven.test.skip=true

#
#   pack with Jetty
#
FROM jetty:11.0.13-jre17-eclipse-temurin

COPY --from=build /home/app/target/jax-rs-template-1.0.0/ /var/lib/jetty/webapps/root/
# RUN java -jar $JETTY_HOME/start.jar --add-module=http2 --approve-all-licenses

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/usr/local/jetty/start.jar"]
