#
#   build
#
FROM maven:3.8.4-openjdk-17-slim as build

COPY src/ /home/app/src
COPY pom.xml /home/app/

RUN mvn -q -f /home/app/pom.xml clean package -Dmaven.test.skip=true

#
#   pack with Tomcat
#
FROM tomcat:10.1.0-jre17-temurin

COPY --from=build /home/app/target/jax-rs-template-1.0.0/ /usr/local/tomcat/webapps/ROOT/

ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

EXPOSE 8080
ENTRYPOINT ["catalina.sh", "run"]